main: mc.fabioneto.places.PlacesPlugin
name: Places
version: 1.19
commands:
  warp: { }
  warps: { }
  setwarp: { }
  delwarp: { }
permissions:
  warps.admin:
    default: op
    children:
      warps.command.setwarp: true
      warps.command.delwarp: true
      warps.delay.0: true
