main: mc.fabioneto.places.PlacesPlugin
name: Places
version: 1.19
commands:
  warp: { }
  warps: { }
  setwarp: { }
  delwarp: { }
  home: { }
  homes: { }
  sethome: { }
  delhome: { }
permissions:
  places.admin:
    default: op
    children:
      places.command.setwarp: true
      places.command.delwarp: true
      places.delay.0: true
