# Languages currently available: 'en', 'pt'.
language: 'en'
# Autosave, in minutes (0 to disable).
autosave: 5
# TTL (time-to-live) in days.
# How many days a player can be offline before being purged/removed from database (0 to disable).
# Players will be purged when loading/saving data.
ttl: 60
# Maximum delay (in seconds) a teleportation may take. Can be adjusted with permissions.
max-delay: 5
# Should players be able to move during teleportation.
movement-allowed: false
# Should players be able to lose health during teleportation.
damage-allowed: false
# Command blocker during teleportation.
cmd-blocker:
  # Command-blocker mode: 0 to disable, 1 (positive) for whitelist and -1 (negative) for blacklist.
  mode: 1
  # List of commands to allow/deny (whitelist/blacklist).
  list: [ 'l', 'g', '.', 'a' ]
