main: mc.fabioneto.warps.WarpsPlugin
name: Warps
version: 1.19
commands:
  warp: {}
  warps: {}
  setwarp: {}
  delwarp: {}
permissions:
  warps.admin:
    default: op
    children:
      warps.command.setwarp: true
      warps.command.delwarp: true
      warps.delay.0: true
